src/Entity/Participant.php
<?php

namespace App\Entity;

use App\Repository\ParticipantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Mapping\ClassMetadata;


/**
 * @Vich\Uploadable
 */
#[ORM\Entity(repositoryClass: ParticipantRepository::class)]
class Participant implements UserInterface, PasswordAuthenticatedUserInterface, \Serializable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $username;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $prenom;

    #[Assert\Regex(
        pattern: '/^(?:(?:\+|00)33[\s.-]{0,3}(?:\(0\)[\s.-]{0,3})?|0)[1-9](?:(?:[\s.-]?\d{2}){4}|\d{2}(?:[\s.-]?\d{3}){2})$/',
        message: "Le format du téléphone n'est pas bon",
        match: true,
    )]
    #[ORM\Column(type: 'string', nullable: true)]
    private $telephone;

    #[Assert\Regex(
        pattern: "/^[\w\.]+@([\w]+\.)+[\a-z]{2,4}$/",
        message: "Le format du mail n'est pas bon",
        match: true,
    )]
    #[ORM\Column(type: 'string', length: 255, unique: true)]
    private $mail;

    #[ORM\Column(type: 'boolean')]
    private $administrateur;

    #[ORM\Column(type: 'boolean')]
    private $actif;

    #[ORM\ManyToMany(targetEntity: Sortie::class, mappedBy: 'participants')]
    private $sorties;

    #[ORM\OneToMany(mappedBy: 'organisateur', targetEntity: Sortie::class, orphanRemoval: true)]
    private $sorties_organisateur;

    #[ORM\ManyToOne(targetEntity: Site::class, inversedBy: 'participants')]
    #[ORM\JoinColumn(nullable: false)]
    private $site;


    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $images;

    /**
     * @Vich\UploadableField(mapping="images_profil", fileNameProperty="images")
     * @param File|UploadedFile|null $fichierImage
     */
    private $fichierImage;


    public function __construct()
    {
        $this->sorties = new ArrayCollection();
        $this->sorties_organisateur = new ArrayCollection();
    }


    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getAdministrateur(): ?bool
    {
        return $this->administrateur;
    }

    public function setAdministrateur(bool $administrateur): self
    {
        $this->administrateur = $administrateur;

        return $this;
    }

    public function __toString()
    {
        return $this->username;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    /**
     * @return Collection|Sortie[]
     */
    public function getSorties(): Collection
    {
        return $this->sorties;
    }

    public function addSorty(Sortie $sorty): self
    {
        if (!$this->sorties->contains($sorty)) {
            $this->sorties[] = $sorty;
            $sorty->addParticipant($this);
        }

        return $this;
    }

    public function removeSorty(Sortie $sorty): self
    {
        if ($this->sorties->removeElement($sorty)) {
            $sorty->removeParticipant($this);
        }

        return $this;
    }

    /**
     * @return Collection|Sortie[]
     */
    public function getSortiesOrganisateur(): Collection
    {
        return $this->sorties_organisateur;
    }

    public function addSortiesOrganisateur(Sortie $sortiesOrganisateur): self
    {
        if (!$this->sorties_organisateur->contains($sortiesOrganisateur)) {
            $this->sorties_organisateur[] = $sortiesOrganisateur;
            $sortiesOrganisateur->setOrganisateur($this);
        }

        return $this;
    }

    public function removeSortiesOrganisateur(Sortie $sortiesOrganisateur): self
    {
        if ($this->sorties_organisateur->removeElement($sortiesOrganisateur)) {
            // set the owning side to null (unless already changed)
            if ($sortiesOrganisateur->getOrganisateur() === $this) {
                $sortiesOrganisateur->setOrganisateur(null);
            }
        }

        return $this;
    }

    public function getSite(): ?Site
    {
        return $this->site;
    }

    public function setSite(?Site $site): self
    {
        $this->site = $site;

        return $this;
    }


    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string)$this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

//test

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return mixed
     */
    public function getFichierImage(): mixed
    {
        return $this->fichierImage;
    }

    public function getImages(): ?string
    {
        return $this->images;
    }

    public function setImages(?string $images): self
    {
        $this->images = $images;

        return $this;
    }

    public function setFichierImage(?File $fichier = null): self
    {
        $this->fichierImage = $fichier;
        if ($fichier) {
            $this->username;
            $this->images = $fichier->getFilename();
        }
        return $this;
    }

    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
        ));
    }

    public function unserialize($serialized)
    {
        list(
            $this->id,
            $this->username,
            $this->password,
            ) = unserialize($serialized);
    }

    public function isGranted($role)
    {
        return in_array($role, $this->getRoles());
    }
}

src/Entity/Sortie.php
<?php

namespace App\Entity;

use App\Repository\SortieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SortieRepository::class)]
class Sortie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'datetime')]
    private $dateHeureDebut;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $duree;

    #[ORM\Column(type: 'datetime')]
    private $dateLimiteInscription;

    #[ORM\Column(type: 'integer')]
    private $nbInscriptionsMax;

    #[ORM\Column(type: 'text', nullable: true)]
    private $InfosSortie;

    #[ORM\ManyToMany(targetEntity: Participant::class, inversedBy: 'sorties')]
    private $participants;

    #[ORM\ManyToOne(targetEntity: Participant::class, inversedBy: 'sorties_organisateur')]
    #[ORM\JoinColumn(nullable: false)]
    private $organisateur;

    #[ORM\ManyToOne(targetEntity: Site::class, inversedBy: 'sorties')]
    #[ORM\JoinColumn(nullable: false)]
    private $site;

    #[ORM\ManyToOne(targetEntity: Etat::class, inversedBy: 'sorties')]
    #[ORM\JoinColumn(nullable: false)]
    private $etat;

    #[ORM\ManyToOne(targetEntity: Lieu::class, inversedBy: 'sorties')]
    #[ORM\JoinColumn(nullable: false)]
    private $lieu;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $motif;

    public function __construct()
    {
        $this->participants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateHeureDebut(): ?\DateTimeInterface
    {
        return $this->dateHeureDebut;
    }

    public function setDateHeureDebut(\DateTimeInterface $dateHeureDebut): self
    {
        $this->dateHeureDebut = $dateHeureDebut;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(?int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getDateLimiteInscription(): ?\DateTimeInterface
    {
        return $this->dateLimiteInscription;
    }

    public function setDateLimiteInscription(\DateTimeInterface $dateLimiteInscription): self
    {
        $this->dateLimiteInscription = $dateLimiteInscription;

        return $this;
    }

    public function getNbInscriptionsMax(): ?int
    {
        return $this->nbInscriptionsMax;
    }

    public function setNbInscriptionsMax(int $nbInscriptionsMax): self
    {
        $this->nbInscriptionsMax = $nbInscriptionsMax;

        return $this;
    }

    public function getInfosSortie(): ?string
    {
        return $this->InfosSortie;
    }

    public function setInfosSortie(?string $InfosSortie): self
    {
        $this->InfosSortie = $InfosSortie;

        return $this;
    }

    /**
     * @return Collection|Participant[]
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Participant $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
        }

        return $this;
    }

    public function removeParticipant(Participant $participant): self
    {
        $this->participants->removeElement($participant);

        return $this;
    }

    public function getOrganisateur(): ?Participant
    {
        return $this->organisateur;
    }

    public function setOrganisateur(?Participant $organisateur): self
    {
        $this->organisateur = $organisateur;

        return $this;
    }

    public function getSite(): ?Site
    {
        return $this->site;
    }

    public function setSite(?Site $site): self
    {
        $this->site = $site;

        return $this;
    }

    public function getEtat(): ?Etat
    {
        return $this->etat;
    }

    public function setEtat(?Etat $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getLieu(): ?Lieu
    {
        return $this->lieu;
    }

    public function setLieu(?Lieu $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getMotif(): ?string
    {
        return $this->motif;
    }

    public function setMotif(?string $motif): self
    {
        $this->motif = $motif;

        return $this;
    }
}

src/Controller/SortieController.php
<?php

namespace App\Controller;

use App\Entity\Sortie;
use App\Form\SortieType;
use App\Repository\EtatRepository;
use App\Repository\ParticipantRepository;
use App\Repository\SiteRepository;
use App\Repository\SortieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/sortie')]
class SortieController extends AbstractController
{
    #[Route('/admin', name: 'sortie_index', methods: ['GET'])]
    public function index(SortieRepository $sortieRepository): Response
    {
        return $this->render('sortie/index.html.twig', [
            'sorties' => $sortieRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'sortie_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, ParticipantRepository $participantRepository, EtatRepository $etatRepository, SiteRepository $siteRepository, SortieRepository $sortieRepository): Response
    {

        $sortie = new Sortie();
        $form = $this->createForm(SortieType::class, $sortie);
        $form->handleRequest($request);
        $erreur = false;

        if ($form->isSubmitted() && $form->isValid()) {
            if (($sortie->getDateLimiteInscription() <= new \DateTime()) or ($sortie->getDateHeureDebut() <= $sortie->getDateLimiteInscription())) {
                $this->addFlash('error', "Vous ne pouvez pas mettre une date inférieure à la date du jour. La date limite d'inscription doit être inférieure à la date de la sortie");
                $erreur = true;
            }
            if ($sortie->getNbInscriptionsMax() <= 0) {
                $this->addFlash('error', 'Le nombre de places doit être supérieur à 0');
                $erreur = true;
            }
            if ($sortie->getDuree() <= 0) {
                $this->addFlash('error', 'La durée doit être supérieure à 0');
                $erreur = true;
            }

            if ($erreur == false) {
                $sortie->setOrganisateur($participantRepository->findOneBy(['username' => $this->getUser()->getUserIdentifier()]));
                $sortie->setEtat($etatRepository->findOneBy(['libelle' => 'Créée']));
                $entityManager->persist($sortie);
                $entityManager->flush();
                $sorties = $sortieRepository->findAll();
                $sites = $siteRepository->findAll();
                return $this->redirectToRoute('main_accueil', [
                    "sorties" => $sorties,
                    "sites" => $sites,

                ], Response::HTTP_SEE_OTHER);
            }
        }

        return $this->renderForm('sortie/new.html.twig', [
            'sortie' => $sortie,
            'form' => $form,
        ]);
    }


    #[Route('/{id}', name: 'sortie_delete', methods: ['POST'])]
    public function delete(Request $request, Sortie $sortie, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $sortie->getId(), $request->request->get('_token'))) {
            $entityManager->remove($sortie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('sortie_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/annulerRedirection/{idSortie}', name: 'annuler_sortie_admin')]
    public function annulerRedirection($idSortie,
                                       SortieRepository $sortieRepository,

    ): Response
    {
        $laSortie = $sortieRepository->findOneBy(['id' => $idSortie], []);
        $annuler = true;
        return $this->render('sortie/annuler.html.twig', [

            'sortie' => $laSortie,
            'annuler' => $annuler,
        ]);

    }

}

templates/sortie/_delete_form.html.twig
<form method="post" action="{{ path('sortie_delete', {'id': sortie.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer cette ville?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sortie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/sortie/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn-primary">Enregistrer</button>
{{ form_end(form) }}

templates/sortie/annuler.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annuler une sortie{% endblock %}

{% block stylesheets %}
{% endblock %}
{% block body %}
    <div class="container">
        <h1 class="text-center mt-5 mb-5">Annuler une sortie</h1>


        <div class="row">
            <div class="col-md-4 col-2"></div>
            <div class="col-md-3 col-lg-2 col-sm-4 col-4">
                <label for="resultatNom">Nom de la sortie :</label>
            </div>
            <div class="col-md-4  col-5">
                <p id="resultatNom">{{ sortie.nom }}</p>
            </div>

        </div>


        <div class="dateSortie">
            <div class="row">
                <div class="col-md-4 col-2"></div>
                <div class="col-md-3 col-lg-2 col-sm-4 col-4">
                    <label for="resultatDateSortie">Date de la sortie :</label>
                </div>
                <div class="col-md-4  col-5">
                    <p id="resultatDateSortie">{{ sortie.dateHeureDebut.format('d/m/Y h:m') }}</p>
                </div>
            </div>
        </div>
        <div class="infosDroite">
            <div class="villeOrganisatrice">
                <div class="row">
                    <div class="col-md-4 col-2"></div>
                    <div class="col-md-3 col-lg-2 col-sm-4 col-4">
                        <p class="labelVilleOrganisatrice">Ville organisatrice :</p>
                    </div>
                    <div class="col-md-4 col-5">
                        <p class="resultatVilleOrganisatrice">{{ sortie.site.nom }}</p>
                    </div>
                </div>
            </div>

            <div class="lieu">
                <div class="row">
                    <div class="col-md-4 col-2"></div>
                    <div class="col-md-3 col-lg-2 col-sm-4 col-4">
                        <p class="labelLieu">Lieu :</p>
                    </div>
                    <div class="col-md-4  col-5">
                        <p class="resultatLieu">{{ sortie.lieu.nom }}</p>
                    </div>
                </div>
            </div>
            <form action="{{ path('main_annuler', {'idSortie': sortie.id}) }}" method="post">
                <div class="motif">
                    <div class="row">
                        <div class="col-md-4 col-2"></div>
                        <div class="col-md-3 col-lg-2 col-sm-4 col-4">
                            <label for="story">Motif :</label>
                        </div>
                        <div class="col-md-4  col-5">
                            <textarea id="story" name="motif"
                                      rows="5"></textarea>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 col-2"></div>
                    <div class="col-md-3 col-lg-2 col-sm-4 col-4">
                        <button type="submit" class="btn btn-success btn-lg">Enregistrer</button>
                    </div>

                    <div class="col-md-4 col-5">
                        <a href="{{ path('main_accueil') }}" class="btn btn-danger btn-lg">Annuler</a>
                    </div>
                </div>
            </form>
        </div>
        <div class="mt-4"></div>

    </div>
{% endblock %}

templates/sortie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gérer les sorties{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="mb-5 text-center">Gérer les sorties</h1>

        <div class="table-responsive table-wrapper-scroll-y my-custom-scrollbar-admin mb-sm-5 ">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Nom de la sortie</th>
                    <th scope="col">Date de la sortie</th>
                    <th scope="col">Clôture</th>
                    <th>Duree</th>
                    <th scope="col">inscrits/places</th>
                    <th>actions</th>
                </tr>
                </thead>
                <tbody>
                {% for sortie in sorties %}
                    {% if sortie.etat.libelle != 'Annulée' %}
                    <tr>
                        <td>{{ sortie.id }}</td>
                        <td>{{ sortie.nom }}</td>
                        <td>{{ sortie.dateHeureDebut ? sortie.dateHeureDebut|date('d/m/Y h:m') : '' }}</td>
                        <td>{{ sortie.dateLimiteInscription ? sortie.dateLimiteInscription|date('d/m/Y h:m') : '' }}</td>
                        <td>{{ sortie.duree }} minutes</td>
                        <td>{{ sortie.participants|length }}/{{ sortie.nbInscriptionsMax }}</td>
                        <td>
                            <a href="{{ path('annuler_sortie_admin', {'idSortie': sortie.id}) }}"
                               class="btn btn-success" type="button">Annuler</a>
                        </td>
                    </tr>
                    {% endif %}
                {% else %}
                    <tr>
                        <td colspan="8">Pas de sorties trouvées</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/sortie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sortie{% endblock %}

{% block stylesheets %}
{% endblock %}
{% block body %}
    <div class="container">
        <h1 class="text-center mt-5 mb-5">Afficher une sortie</h1>
        <div class="row">
            <div class="col-xl-6 col-lg-12">

                <div class="nom">
                    <div class="row">
                        <div class="col-2"></div>
                        <div class="col-4">
                            <label for="resultatNom">Nom de la sortie :</label>
                        </div>
                        <div class="col-6">
                            <p id="resultatNom">{{ sortie.nom }}</p>

                        </div>
                    </div>
                </div>
                <div class="dateSortie">
                    <div class="row">
                        <div class="col-2"></div>
                        <div class="col-4">
                            <label for="resultatDateSortie">Date et heure de la sortie :</label>
                        </div>
                        <div class="col-6">
                            <p id="resultatDateSortie">{{ sortie.dateHeureDebut.format('d/m/Y h:m') }}</p>
                        </div>
                    </div>
                </div>

                <div class="dateCloture">
                    <div class="row">
                        <div class="col-2"></div>
                        <div class="col-4">
                            <label for="resultatDateCloture">Date limite d'inscription :</label>
                        </div>
                        <div class="col-6">
                            <p id="resultatDateCloture">{{ sortie.dateLimiteInscription.format('d/m/Y h:m') }}</p>
                        </div>
                    </div>
                </div>

                <div class="nbDePlaces">
                    <div class="row">
                        <div class="col-2"></div>
                        <div class="col-4">

                            <label for="resultatNbDePlaces">Nombre de places :</label>

                        </div>
                        <div class="col-6">

                            <p id="resultatNbDePlaces">{{ sortie.nbInscriptionsMax }}</p>
                        </div>
                    </div>
                </div>

                <div class="duree">
                    <div class="row">
                        <div class="col-2"></div>
                        <div class="col-4">
                            <label for="resultatDuree">Durée :</label>
                        </div>
                        <div class="col-6">

                            <p class="resultatDuree">{{ sortie.duree }} minutes</p>
                        </div>
                    </div>
                </div>

                <div class="descriptionEtInfos">
                    <div class="row">
                        <div class="col-2"></div>
                        <div class="col-4">
                            <label for="resultatNbDePlaces">Description et infos :</label>
                        </div>
                        <div class="col-6">
                            <p class="resultatDescriptionEtInfos">{{ sortie.infosSortie }}</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-6 col-lg-12">

                <div class="infosDroite">

                    <div class="villeOrganisatrice">
                        <div class="row">
                            <div class="col-2"></div>
                            <div class="col-4">
                                <p class="labelVilleOrganisatrice">Ville organisatrice :</p>
                            </div>
                            <div class="col-6">
                                <p class="resultatVilleOrganisatrice">{{ sortie.site.nom }}</p>
                            </div>
                        </div>
                    </div>

                    <div class="lieu">
                        <div class="row">
                            <div class="col-2"></div>
                            <div class="col-4">
                                <p class="labelLieu">Lieu :</p>
                            </div>
                            <div class="col-6">
                                <p class="resultatLieu">{{ sortie.lieu.nom }}</p>
                            </div>
                        </div>
                    </div>


                </div>
                <div class="rue">
                    <div class="row">
                        <div class="col-2"></div>
                        <div class="col-4">
                            <p class="labelRue">Rue :</p>
                        </div>
                        <div class="col-6">

                            <p class="resultatRue">{{ sortie.lieu.rue }}</p>
                        </div>
                    </div>
                </div>

                <div class="codePostal">
                    <div class="row">
                        <div class="col-2"></div>
                        <div class="col-4">
                            <p class="labelCodePostal">Code postal :</p>
                        </div>
                        <div class="col-6">

                            <p class="resultatCodePostal">{{ sortie.lieu.ville.codePostal }}</p>
                        </div>
                    </div>
                </div>

                <div class="latitude">
                    <div class="row">
                        <div class="col-2"></div>
                        <div class="col-4">
                            <p class="labelLatitude">Latitude :</p>
                        </div>
                        <div class="col-6">
                            <p class="resultatLatitude">{{ sortie.lieu.latitude }}</p>
                        </div>
                    </div>
                </div>
                <div class="longitude">
                    <div class="row">
                        <div class="col-2"></div>
                        <div class="col-4">
                            <p class="labelLongitude">Longitude :</p>
                        </div>

                        <div class="col-6">
                            <p class="resultatLongitude">{{ sortie.lieu.longitude }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mx-5 mt-5">
        <h3>Liste des participants inscrits</h3>
        <div class="tableParticipants">
            <div class="table-responsive table-wrapper-scroll-y my-custom-scrollbar-participants">
                <table class="table table-bordered mb-0">
                    <thead>
                    <tr>
                        <th scope="col">Pseudo</th>
                        <th scope="col">Nom</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for eachParticipant in sortie.participants %}
                        <tr>
                            <td>{{ eachParticipant.userIdentifier }}</td>
                            <td>{{ eachParticipant.prenom }} {{ eachParticipant.nom|upper }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="d-block d-sm-none">
            <div class="mb-5"></div>
        </div>
        <div class="d-none d-sm-block d-md-none">
            <div class="mb-5"></div>
        </div>
        <div class="d-none d-md-block d-lg-none">
            <div class="mb-5"></div>
        </div>
        <div class="d-none d-lg-block d-xl-none">
            <div class="mb-5"></div>
        </div>
    </div>
    <div class="container">
        <div class="mt-5"></div>
        <div class="d-flex justify-content-center">
            <a href="{{ path('main_accueil') }}" class="btn btn-lg btn-success" type="button">Retour</a>
        </div>
        <div class="d-block d-sm-none">
            <div class="mb-5"></div>
        </div>
        <div class="d-none d-sm-block d-md-none">
            <div class="mb-5"></div>
        </div>
        <div class="d-none d-md-block d-lg-none">
            <div class="mb-5"></div>
        </div>
        <div class="d-none d-lg-block d-xl-none">
            <div class="mb-5"></div>
        </div>
        <div class=".d-none .d-xl-block .d-xxl-none">
            <div class="mb-5"></div>
        </div>
    </div>
{% endblock %}